- name: restart postfix
  service: name=postfix state=restarted

- name: restart dovecot
  service: name=dovecot state=restarted

- name: restart amavis-new
  service: name=amavis state=restarted

- name: restart amavisd-milter
  service: name=amavisd-milter state=restarted

- name: restart postgrey
  service: name=postgrey state=restarted

- name: restart clamav
  service: name=clamav-daemon state=restarted

- name: restart opendkim
  service: name=opendkim state=restarted
